export const openings = [
  {
    id: "italiana", code: "ITA", manualNumber: 1,
    title: "Apertura Italiana", shortTitle: "La Italiana", version: "2",
    accent: "#008C45", focus: "#38A76B", boardDark: "#6F9278",
    preview: { fen: "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3", line: "1.e4 e5 2.Cf3 Cc6 3.Ac4", lastMove: ["f1", "c4"] },
    quote: { text: "Ayuda a tus piezas para que ellas puedan ayudarte.", author: "Paul Morphy", years: "1837–1884", nationality: "USA" },
    sourceDir: "italiana", csv: "posiciones_ITA_completo.csv", pgn: "partidas_modelo_ITA.pgn", expectedComplete: true,
    lab: { adjective: "Italiana", article: "La Italiana", notation: "1.e4 e5 2.Cf3 Cc6 3.Ac4 Ac5", principles: ["Centro", "Desarrollo", "Enroque", "Ruptura d4"], identity: "La diagonal italiana", lead: "Domina la Apertura Italiana entendiendo el centro, la seguridad del rey y la coordinación de tus piezas.", baseIndex: 2 },
  },
  {
    id: "espanola", code: "ESP", manualNumber: 2,
    title: "Apertura Española o Ruy López", shortTitle: "La Española", version: "2.3",
    accent: "#AA151B", focus: "#D14A4F", boardDark: "#B66A67",
    preview: { fen: "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3", line: "1.e4 e5 2.Cf3 Cc6 3.Ab5", lastMove: ["f1", "b5"] },
    quote: { text: "No creo en la psicología. Creo en las buenas jugadas.", author: "Bobby Fischer", years: "1943–2008", nationality: "USA" },
    sourceDir: "espanola", csv: "posiciones_ESP_v2.3.csv", pgn: "partidas_modelo_ESP_v2.3.pgn", expectedComplete: true, pgnLocalized: true,
    lab: { adjective: "Española", article: "La Española", notation: "1.e4 e5 2.Cf3 Cc6 3.Ab5 a6", principles: ["Presión e5", "Alfil español", "Maniobras", "Ruptura d4"], identity: "La presión española", lead: "Domina la Apertura Española entendiendo la presión central, las maniobras y el momento de jugar d4.", baseIndex: 2 },
  },
  {
    id: "escocesa", code: "ESC", manualNumber: 3,
    title: "Apertura Escocesa", shortTitle: "La Escocesa", version: "1.4",
    accent: "#0065BD", focus: "#3F8DCA", boardDark: "#6C8FB2",
    preview: { fen: "r1bqkbnr/pppp1ppp/2n5/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq d3 0 3", line: "1.e4 e5 2.Cf3 Cc6 3.d4", lastMove: ["d2", "d4"] },
    quote: { text: "El ajedrez es la vida en miniatura. El ajedrez es lucha, el ajedrez es batalla.", author: "Garry Kasparov", years: "1963–", nationality: "RUS" },
    sourceDir: "escocesa", csv: "posiciones_ESC.csv", pgn: "partidas_modelo_ESC.pgn", expectedComplete: true,
    lab: { adjective: "Escocesa", article: "La Escocesa", notation: "1.e4 e5 2.Cf3 Cc6 3.d4 exd4", principles: ["Ruptura d4", "Recaptura", "Líneas abiertas", "Iniciativa"], identity: "La ruptura escocesa", lead: "Domina la Apertura Escocesa entendiendo el centro abierto, el desarrollo con tiempo y la iniciativa.", baseIndex: 2 },
  },
  {
    id: "siciliana", code: "SIC", manualNumber: 4,
    title: "Cómo jugar contra la Defensa Siciliana", shortTitle: "Contra la Siciliana", version: "1.3",
    accent: "#6F2DA8", focus: "#9A5BC3", boardDark: "#8669A0",
    preview: { fen: "rnbqkbnr/pp1ppppp/8/2p5/4P3/2P5/PP1P1PPP/RNBQKBNR b KQkq - 0 2", line: "1.e4 c5 2.c3", lastMove: ["c2", "c3"] },
    quote: { text: "Construye el centro antes de iniciar planes de flanco.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "siciliana", csv: "posiciones_SIC.csv", pgn: "partidas_modelo_SIC.pgn", expectedComplete: true,
    lab: { adjective: "Siciliana", article: "Contra la Siciliana", notation: "1.e4 c5 2.c3 Cf6", principles: ["Alapin", "Centro d4", "Desarrollo", "Casilla d5"], identity: "El centro Alapin", lead: "Responde a la Siciliana con un sistema Alapin coherente, estructuras reconocibles y planes concretos.", baseLabel: "Posición base del sistema Alapin contra la Defensa Siciliana", routeHeading: "Construye el sistema Alapin jugada a jugada", baseIndex: 2 },
  },
  {
    id: "francesa", code: "FRA", manualNumber: 5,
    title: "Cómo jugar contra la Defensa Francesa", shortTitle: "Contra la Francesa", version: "1.2.3",
    accent: "#174A7E", focus: "#3777A8", boardDark: "#587A98",
    preview: { fen: "rnbqkbnr/pp3ppp/4p3/2pp4/3PP3/8/PPPN1PPP/R1BQKBNR w KQkq - 0 4", line: "1.e4 e6 2.d4 d5 3.Cd2 c5", lastMove: ["c7", "c5"] },
    quote: { text: "La cadena de peones indica dónde buscar la ruptura.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "francesa", csv: "posiciones_FRA.csv", pgn: "partidas_modelo_FRA.pgn", expectedComplete: false,
    lab: { adjective: "Francesa", article: "Contra la Francesa", notation: "1.e4 e6 2.d4 d5 3.Cd2", principles: ["Cadena central", "Ruptura c5", "Espacio", "Reagrupación"], identity: "La tensión francesa", lead: "Aprende a jugar contra la Francesa reconociendo cadenas, rupturas y la coordinación que exige cada centro.", baseLabel: "Posición base del repertorio contra la Defensa Francesa", routeHeading: "Construye el repertorio contra la Francesa jugada a jugada", baseIndex: 2 },
  },
  {
    id: "carokann-blancas", code: "CKB", manualNumber: 6,
    title: "Cómo jugar contra la Defensa Caro-Kann", shortTitle: "Contra la Caro-Kann", version: "1.1",
    accent: "#C45112", focus: "#E0793D", boardDark: "#A86F4F",
    preview: { fen: "rnbqkbnr/pp2pppp/2p5/3p4/3PP3/8/PPP2PPP/RNBQKBNR w KQkq d6 0 3", line: "1.e4 c6 2.d4 d5", lastMove: ["d7", "d5"] },
    quote: { text: "El espacio también implica responsabilidad.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "carokann_blancas", csv: "posiciones_CKB.csv", pgn: "partidas_modelo_CKB.pgn", expectedComplete: false,
    lab: { adjective: "Caro-Kann", article: "Contra la Caro-Kann", notation: "1.e4 c6 2.d4 d5 3.e5", principles: ["Avance e5", "Base d4", "Desarrollo", "Ruptura c5"], identity: "El espacio contra la Caro-Kann", lead: "Juega contra la Caro-Kann convirtiendo el espacio central en desarrollo, iniciativa y decisiones claras.", baseLabel: "Posición base del repertorio con blancas contra la Defensa Caro-Kann", routeHeading: "Construye el repertorio contra la Caro-Kann jugada a jugada", baseIndex: 2 },
  },
  {
    id: "carokann-negras", code: "CKN", manualNumber: 7,
    title: "Defensa Caro-Kann contra 1.e4", shortTitle: "La Caro-Kann", version: "1.1.1",
    accent: "#00796B", focus: "#2AA493", boardDark: "#548A82",
    preview: { fen: "rnbqkbnr/pp2pppp/2p5/3p4/3PP3/8/PPP2PPP/RNBQKBNR w KQkq d6 0 3", line: "1.e4 c6 2.d4 d5", lastMove: ["d7", "d5"] },
    quote: { text: "Solidez no significa pasividad: prepara la ruptura correcta.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "carokann_negras", csv: "posiciones_CKN.csv", pgn: "partidas_modelo_CKN.pgn", expectedComplete: false,
    lab: { adjective: "Caro-Kann", article: "La Caro-Kann", notation: "1.e4 c6 2.d4 d5", principles: ["Centro estable", "Alfil c8", "Ruptura c5", "Final sano"], identity: "La solidez activa", lead: "Defiende con la Caro-Kann coordinando el desarrollo con los golpes ...c5 y ...e5.", baseLabel: "Posición base de la Defensa Caro-Kann con negras", routeHeading: "Construye la Defensa Caro-Kann jugada a jugada", baseIndex: 2 },
  },
  {
    id: "escandinava", code: "SCA", manualNumber: 8,
    title: "Defensa Escandinava contra 1.e4", shortTitle: "La Escandinava", version: "1.1",
    accent: "#8B1E3F", focus: "#B64B69", boardDark: "#986273",
    preview: { fen: "rnbqkbnr/ppp1pppp/8/3p4/4P3/8/PPPP1PPP/RNBQKBNR w KQkq d6 0 2", line: "1.e4 d5", lastMove: ["d7", "d5"] },
    quote: { text: "Ataca el centro desde la primera jugada y desarrolla con precisión.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "escandinava", csv: "posiciones_SCA.csv", pgn: "partidas_modelo_SCA.pgn", expectedComplete: false,
    lab: { adjective: "Escandinava", article: "La Escandinava", notation: "1.e4 d5 2.exd5 Dxd5", principles: ["Golpe d5", "Dama activa", "Desarrollo", "Centro sano"], identity: "El desafío inmediato", lead: "Defiende con la Escandinava haciendo que la actividad temprana de la dama sirva al desarrollo.", baseLabel: "Posición base de la Defensa Escandinava", routeHeading: "Construye la Defensa Escandinava jugada a jugada", baseIndex: 2 },
  },
  {
    id: "eslava", code: "SLA", manualNumber: 9,
    title: "Defensa Eslava contra 1.d4", shortTitle: "La Eslava", version: "1.2",
    accent: "#955700", focus: "#C47C20", boardDark: "#8B7048",
    preview: { fen: "rnbqkbnr/pp2pppp/2p5/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3", line: "1.d4 d5 2.c4 c6", lastMove: ["c7", "c6"] },
    quote: { text: "Sostén el centro sin encerrar el desarrollo.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "eslava", csv: "posiciones_SLA.csv", pgn: "partidas_modelo_SLA.pgn", expectedComplete: false,
    lab: { adjective: "Eslava", article: "La Eslava", notation: "1.d4 d5 2.c4 c6", principles: ["Soporte c6", "Alfil c8", "Ruptura c5", "Estructura"], identity: "El centro eslavo", lead: "Defiende con la Eslava sosteniendo d5, liberando el alfil de c8 y eligiendo bien la ruptura.", baseLabel: "Posición base de la Defensa Eslava", routeHeading: "Construye la Defensa Eslava jugada a jugada", baseIndex: 2 },
  },
  {
    id: "gambito-dama-rehusado", code: "GDR", manualNumber: 10,
    title: "Gambito de Dama Rehusado contra 1.d4", shortTitle: "Gambito de Dama Rehusado", version: "1.1",
    accent: "#4B3F72", focus: "#75689C", boardDark: "#716987",
    preview: { fen: "rnbqkbnr/ppp2ppp/4p3/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3", line: "1.d4 d5 2.c4 e6", lastMove: ["e7", "e6"] },
    quote: { text: "Primero consolida; después libera tu posición.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "gambito_dama_rehusado", csv: "posiciones_GDR.csv", pgn: "partidas_modelo_GDR.pgn", expectedComplete: true,
    lab: { adjective: "Gambito de Dama Rehusado", article: "El Gambito de Dama Rehusado", notation: "1.d4 d5 2.c4 e6", principles: ["Centro d5", "Desarrollo", "Ruptura c5", "Liberación e5"], identity: "La fortaleza central", lead: "Domina el Gambito de Dama Rehusado combinando solidez, desarrollo y rupturas liberadoras.", baseLabel: "Posición base del Gambito de Dama Rehusado", routeHeading: "Construye el Gambito de Dama Rehusado jugada a jugada", baseIndex: 2 },
  },
  {
    id: "londres", code: "LON", manualNumber: 11,
    title: "Sistemas contra la Apertura Londres", shortTitle: "Contra el Londres", version: "1.1",
    accent: "#A61E6E", focus: "#CB4D95", boardDark: "#99617F",
    preview: { fen: "rnbqkb1r/pp2pppp/2n2n2/2pp4/3P1B2/4PN2/PPP2PPP/RN1QKB1R w KQkq - 2 5", line: "1.d4 d5 2.Cf3 Cf6 3.Af4 c5 4.e3 Cc6", lastMove: ["b8", "c6"] },
    quote: { text: "Cuestiona el esquema antes de que juegue en automático.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "londres", csv: "posiciones_LON.csv", pgn: "partidas_modelo_LON.pgn", expectedComplete: false,
    lab: { adjective: "Londres", article: "Contra el Londres", notation: "1.d4 d5 2.Cf3 Cf6 3.Af4 c5", principles: ["Golpe c5", "Presión b2", "Desarrollo", "Ruptura e5"], identity: "La respuesta al esquema", lead: "Juega contra el Londres cuestionando su centro y evitando que el blanco complete su plan sin oposición.", baseLabel: "Posición base del repertorio contra el Sistema Londres", routeHeading: "Construye la respuesta al Sistema Londres jugada a jugada", baseIndex: 2 },
  },
  {
    id: "raras", code: "RAR", manualNumber: 12,
    title: "Respuestas contra aperturas poco frecuentes", shortTitle: "Aperturas poco frecuentes", version: "1.1",
    accent: "#2C6E6F", focus: "#4F999A", boardDark: "#66898A",
    preview: { fen: "rnbqkbnr/pppp1ppp/8/4p3/2P5/8/PP1PPPPP/RNBQKBNR w KQkq e6 0 2", line: "1.c4 e5", lastMove: ["e7", "e5"] },
    quote: { text: "Responde por estructura, no por sorpresa.", author: "Mi Repertorio de Ajedrez" },
    sourceDir: "raras", csv: "posiciones_RAR.csv", pgn: "partidas_modelo_RAR.pgn", expectedComplete: true,
    lab: { adjective: "de aperturas poco frecuentes", article: "Aperturas poco frecuentes", notation: "1.c4 e5 2.Cc3 Cf6", principles: ["Centro clásico", "Transposición", "Ruptura d5", "Desarrollo"], identity: "El mapa de transposiciones", lead: "Responde a las aperturas poco frecuentes con principios estables y planes guiados por la estructura.", baseLabel: "Posición base del repertorio contra aperturas poco frecuentes", routeHeading: "Construye respuestas contra aperturas poco frecuentes", baseIndex: 2 },
  },
];

export const openingById = Object.fromEntries(openings.map((opening) => [opening.id, opening]));
